language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
os:
  - linux
  - osx

matrix:
  # Due to insufficient Python support https://github.com/travis-ci/travis-ci/issues/9929
  allow_failures:
    - os: osx

sudo: required
cache: pip
before_install:
  - pip install pytest
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - python3 setup.py test
